// @generated by scripts/sync-vat-rates.mjs —— 请勿手改,改了下次同步会被覆盖。
// 上游:European Commission TEDB (via vatnode/eu-vat-rates-data)
// 抓取日期:2026-07-22
//
// 税率单位为整数基点(bp):19% = 1900,5.5% = 550。

export interface CountryVatData {
  /** 上游给出的英文国名 */
  readonly name: string;
  /** 标准税率(基点) */
  readonly standardBp: number;
  /** 该国全部低税率(含 super-reduced),升序;丹麦这类没有低税率档的为空 */
  readonly reducedBp: readonly number[];
}

export const VAT_RATES_SOURCE = {
  name: 'European Commission TEDB (via vatnode/eu-vat-rates-data)',
  url: 'https://raw.githubusercontent.com/vatnode/eu-vat-rates-data/main/data/eu-vat-rates-data.json',
  version: '2026-07-22',
} as const;

export const VAT_RATES = {
  AT: { name: 'Austria', standardBp: 2000, reducedBp: [490, 1000, 1300, 1900] },
  BE: { name: 'Belgium', standardBp: 2100, reducedBp: [600, 1200] },
  BG: { name: 'Bulgaria', standardBp: 2000, reducedBp: [900] },
  CH: { name: 'Switzerland', standardBp: 810, reducedBp: [260, 380] },
  CY: { name: 'Cyprus', standardBp: 1900, reducedBp: [300, 500, 900] },
  CZ: { name: 'Czech Republic', standardBp: 2100, reducedBp: [1200] },
  DE: { name: 'Germany', standardBp: 1900, reducedBp: [700] },
  DK: { name: 'Denmark', standardBp: 2500, reducedBp: [] },
  EE: { name: 'Estonia', standardBp: 2400, reducedBp: [900, 1300] },
  ES: { name: 'Spain', standardBp: 2100, reducedBp: [400, 1000] },
  FI: { name: 'Finland', standardBp: 2550, reducedBp: [1000, 1350] },
  FR: {
    name: 'France',
    standardBp: 2000,
    reducedBp: [90, 105, 210, 550, 850, 1000, 1300],
  },
  GB: { name: 'United Kingdom', standardBp: 2000, reducedBp: [500] },
  GR: { name: 'Greece', standardBp: 2400, reducedBp: [400, 600, 1300, 1700] },
  HR: { name: 'Croatia', standardBp: 2500, reducedBp: [500, 1300] },
  HU: { name: 'Hungary', standardBp: 2700, reducedBp: [500, 1800] },
  IE: { name: 'Ireland', standardBp: 2300, reducedBp: [900, 1350] },
  IS: { name: 'Iceland', standardBp: 2400, reducedBp: [1100] },
  IT: { name: 'Italy', standardBp: 2200, reducedBp: [400, 500, 1000] },
  LI: { name: 'Liechtenstein', standardBp: 810, reducedBp: [260, 380] },
  LT: { name: 'Lithuania', standardBp: 2100, reducedBp: [500, 1200] },
  LU: { name: 'Luxembourg', standardBp: 1700, reducedBp: [300, 800, 1400] },
  LV: { name: 'Latvia', standardBp: 2100, reducedBp: [500, 1200] },
  MT: { name: 'Malta', standardBp: 1800, reducedBp: [500, 700] },
  NL: { name: 'Netherlands', standardBp: 2100, reducedBp: [900] },
  NO: { name: 'Norway', standardBp: 2500, reducedBp: [1200, 1500] },
  PL: { name: 'Poland', standardBp: 2300, reducedBp: [500, 800] },
  PT: {
    name: 'Portugal',
    standardBp: 2300,
    reducedBp: [600, 1300, 1600, 2200],
  },
  RO: { name: 'Romania', standardBp: 2100, reducedBp: [1100] },
  SE: { name: 'Sweden', standardBp: 2500, reducedBp: [600, 1200] },
  SI: { name: 'Slovenia', standardBp: 2200, reducedBp: [500, 950] },
  SK: { name: 'Slovakia', standardBp: 2300, reducedBp: [500, 1900] },
} as const satisfies Record<string, CountryVatData>;
